apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-77gi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-77gi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-77gi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-77gi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-77gi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-epxo-tenant/rhtap-demo-app/hacbs-test-project-77gi@sha256:32a7f5f5347b847751207cd1e8289ed2f2fa148b688026efa557ec988cc4aa00
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
