apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-77gi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-epxo-tenant/rhtap-demo-app/hacbs-test-project-77gi@sha256:32a7f5f5347b847751207cd1e8289ed2f2fa148b688026efa557ec988cc4aa00
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
